os: osx
osx_image: xcode9.2

language: objective-c
xcode_workspace: objc.xcworkspace
xcode_scheme: objc-debug

git:
  depth: 3
  submodules: false
  
branches:
  only:
    - master
    - feature-travis-ci

before_install:
  - brew install git-lfs
  
install: true

before_script:
  - git lfs pulll
