os: osx
osx_image: xcode9.2

language: objective-c

env:
  global:
    - XCODE_WORKSPACE="objc.xcworkspace"
    - XCODE_SCHEME="objc-debug"
    
xcode_workspace: ${XCODE_WORKSPACE}
xcode_scheme: ${XCODE_SCHEME}

git:
  depth: 3
  submodules: false
  
branches:
  only:
    - /.*/

before_install:
  - brew install git-lfs
  
install: true

before_script:
  - git lfs pulll
  
script:
  - xcodebuild clean build  -workspace ${XCODE_WORKSPACE} -scheme ${XCODE_SCHEME}
